name: Generate Resume PDF

on:
  push:
    branches:
      - master
  workflow_dispatch: # Permite rodar a action manualmente !

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências do projeto
        run: npm install

      - name: Instalar dependências de SO para o Puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi-dev libxtst6 libcups2 libnss3 libxrandr2 libasound2t64 libatk1.0-0 libgtk-3-0

      - name: Gerar PDF
        run: node generate.js

      - name: Upload do PDF como artefato
        uses: actions/upload-artifact@v4
        with:
          name: curriculo-gustavo
          path: resume.pdf
          retention-days: 5
